name: GitHub Classroom Workflow
on: [push]
permissions:
  checks: write
  actions: read
  contents: read
  
jobs:
  testing:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: "Installing dependencies"
        run: python3 -m pip install -r requirements.txt
        shell: bash

      - name: Checking with doctest
        run: python3 -m doctest src/*.py
        shell: bash

      - name: Checking with pytest
        run: |
          if src/test_*.py 2> /dev/null; then python3 -m pytest src; fi
          if src/*_test.py 2> /dev/null; then python3 -m pytest src; fi
        shell: bash
